### ISSUE TITLE
No mention of the need to specify public permissions

### ISSUE THREAD

**Issue by AlexandrePicosson** [SubstraFoundation/substra#124]
https://github.com/SubstraFoundation/substra/blob/c6bae9cb15388e186341dbb9f08be25e8ab762c1/substra/sdk/client.py#L726-L728

You could replace it by this code for better user information as the error thrown if you forget the public permissions is not very informative (400 Bad request). 
```python
"out_trunk_model_permissions": {
                    "public": bool,
                    "authorized_ids": list[str],
                },
```

**Comment by jmorel** [comment]
This has been fixed in https://github.com/SubstraFoundation/substra-backend/pull/188 !
