### ISSUE TITLE
Update the displayed url in substra cli --help

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/substra#134]
When running the command `substra --help` on substra v. 0.3.0, the url displayed is pointing towards an archived repository. It would be great to update it from <https://github.com/SubstraFoundation/substra-cli> to <https://github.com/SubstraFoundation/substra>!

**Comment by jmorel** [comment]
This has been fixed in #107 and will show up in the next pypi release!

**Comment by natct10** [comment]
Awesome!
