### ISSUE TITLE
keyrings.alt requirement necessary for Linux machines

### ISSUE THREAD

**Issue by jeandut** [SubstraFoundation/substra#165]
When registering new samples with substra on a Linux machine the error `samples:keyrings.error.NoKeyRingsError` sometimes forces the user to install `keyrings.alt`. 
But it seems like it is might not be a recommended solution, any idea on that ?

**Comment by jmorel** [comment]
There is a current attempt at removing the need for keyring altogether #138 but it's not validated nor merged yet.
