### ISSUE TITLE
Docs: update local install with skaffold setup

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra#17]
Should we:
- keep the instructions for docker-compose and add skaffold instructions
- or, replace docker-compose instructions with skaffold instructions

For skaffold, we should pay attention to the settings required to mount correctly the volume shared between the localhost and the backend pods.

**Comment by AurelienGasser** [comment]
My understanding about our current policy is that we have 2 ways for developers to run the platform locally: skaffold and docker-compose. So, _for developers_, we have 2 sets of instructions (or at least, we're going in that direction).

Concerning the "local install" doc, and assuming it is a set of instructions _for non-developer users_, and that these instructions come _in addition_ to the existing developer instructions, is it necessary to support both docker-compose and skaffold there ?

**Comment by samlesu** [comment]
That's a very good question! Users of substra could also be developers, so I think we need to distinguish:
1. developers of the substra platform
2. users of substra

I would say (to be confirmed) that the documentation inside this repository is targeting mainly the second category of people.
