### ISSUE TITLE
Handle more gracefully adding the same testtuple twice

### ISSUE THREAD

**Issue by jeandut** [SubstraFoundation/substra#172]
Currently when adding the same testtuple twice the SDK raises the error:
`substra.sdk.exceptions.AlreadyExists: Object with key(s) 'A' already exists.`
Maybe one could catch the error and return a warning instead like: "testtupple already submitted " while returning the same dict the previous testtuple returned ?

**Comment by samlesu** [comment]
To do that, you can use the option `exist_ok=True` when adding a testtuple (by default it's set to False). It will always return a testtuple even if it already exists. If it already exists a log warning will be emitted.

**Comment by jeandut** [comment]
Ok closing it then !
