### ISSUE TITLE
Add command to delete assets [enhancement]

### ISSUE THREAD

**Issue by chrisalexandrepena** [SubstraFoundation/substra#173]
It would be great to be able to actualy cancel the exectution of an asset running on substra (as I unsderstand `substra cancel` only serves to cancel compute plans).
Also could we get a `substra delete` command that allows us to remove unwanted assets from substra (failed traintuples for example)?

**Comment by samlesu** [comment]
Thanks Chris for your suggestion.
We plan to have a filtering based on tag or on metadata to hide some assets but deleting asset is against Substra design.

**Comment by natct10** [comment]
> Thanks Chris for your suggestion.
> We plan to have a filtering based on tag or on metadata to hide some assets but deleting asset is against Substra design.

Sounds great!
