### ISSUE TITLE
Subtra SDK documentation: text from add_traintuple copied in add_testtuple

### ISSUE THREAD

**Issue by celinejacques** [SubstraFoundation/substra#174]
The text in the read me and documentation of the SDK to describe the function `add_testtuple` seems to be copied from `add_traintuple`. It may be updated to describe `add_testtuple`. 

https://github.com/SubstraFoundation/substra/blob/master/references/sdk.md

**Comment by jmorel** [comment]
It looks like the descriptions are correct, could you give more details about what makes you think there's duplicate content?

**Comment by celinejacques** [comment]
I think in this phrase `An AlreadyExists exception will be raised if a traintuple already exists that:` for `add_testtuple`, it's about `testtuple` which already exists. But I could be wrong.

**Comment by jmorel** [comment]
Ah yes, good catch, I'll fix it right away!
