### ISSUE TITLE
[Feature request] Remove the 'version' from the client

### ISSUE THREAD

**Issue by Esadruhn** [SubstraFoundation/substra#208]
## Current

There is a parameter `version` in the `__init__` and `from_config_file` functions of the Client. This parameters refers to a versioning to the API, but there is only one version available (and it is not in the works to change that)

## What the feature changes

Remove 'version' from those function's signatures, hardcode it where it is needed.  
It removes a confusing parameter for the user.

**Comment by samlesu** [comment]
This is a good idea. The 'version' option will be added when the backend will support at least two API versions :)

**Comment by samlesu** [comment]
Let's go on this :)
