### ISSUE TITLE
titanic: Missing keyrings.alt

### ISSUE THREAD

**Issue by AurelienGasser** [SubstraFoundation/substra#22]
When running the titanic examples with skaffold, I get an error related to keyring.alt.

Running the command below fixes it:

```
pip install keyrings.alt
```

**Comment by AurelienGasser** [comment]
@GuillaumeCisco Am I missing something?

**Comment by GuillaumeCisco** [comment]
What Operating System are you using?
You shouldn't have to install `keyrings.alt` if you are on a classic operating system.
It is commonly used for test server or very basic OS (i.e some docker image).

Can you provide more data about this issue?
When did it appear?
How to reproduce it.

Thank you,

**Comment by AurelienGasser** [comment]
@GuillaumeCisco I tried to repro, in vain. 

I'm going to close this for now. I'll re-open if I manage to get a repro.
