### ISSUE TITLE
Docs: Missing a field in client doc

### ISSUE THREAD

**Issue by Klexounet** [SubstraFoundation/substra#36]
I think the field `rank` here is missing in fuction `add_traintuple`

[link](https://github.com/SubstraFoundation/substra/blob/1bcba361f84bfb0810e4b86748f2f57c68b9f713/substra/sdk/client.py#L339)

**Comment by jmorel** [comment]
You're absolutely right, would you like to submit a PR to fix it?

**Comment by Kelvin-M** [comment]
@Klexounet  It's fixed in master https://github.com/SubstraFoundation/substra/blob/master/substra/sdk/client.py#L412
