### ISSUE TITLE
Make it clearer that we should use the compute plan method to create tuples

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra#43]
Ideas:
1. Documentation / SDK:
- add a warning, or recommended section in the `add_testtuple` and `add_traintuple` methods docstrings
- or, deprecate add_testtuple / add_traintuple methods (make it private? add a deprecation warning at runtime...)

2. Examples should only use compute plans?

**Comment by Kelvin-M** [comment]
I do not understand why user must use a compute plan to add a `traintuple` or a `testtuple`. If we just want to run a unique train step using a compute plan can be confusing no ?

**Comment by samlesu** [comment]
Yes, you're right. I will close the issue.
