### ISSUE TITLE
Add dataset with empty file

### ISSUE THREAD

**Issue by maeldebon** [SubstraFoundation/substra#51]
When trying to add a dataset with an empty description or data_opener, the error is always the same. 
It should be good to precise which file is empty in the error message.

EDIT: The reason is finally displayed, but in JSON.

```
Error: Request failed: InvalidRequest: 400 Client Error: Bad Request for url: http://substra-backend.node-1.com/data_manager/: [{'description': ['The submitted file is empty.']}]
```

**Comment by jmorel** [comment]
Could you add an example of the error to the main description? Just looking at the code I'm having trouble figuring out what is happening.

**Comment by maeldebon** [comment]
> Could you add an example of the error to the main description? Just looking at the code I'm having trouble figuring out what is happening.

I added it! 🙂

**Comment by jmorel** [comment]
Thanks! So in the end it looks like this is a more of a formatting issue related to #35

**Comment by jmorel** [comment]
@maeldebon I'm closing this PR in favor of #147 where we can have a discussion about error formatting.
