### ISSUE TITLE
New cancel compute plan command

### ISSUE THREAD

**Issue by jmorel** [SubstraFoundation/substra#55]
In link with the "fail fast" mission, we need to have in both the cli and sdk cancel compute plan commands / methods with the following signatures:

In the cli:
```
$ substra cancel compute_plan <compute_plan_id>
```
This command should support the same options as get compute plan.

In the sdk:
```python
client.cancel_compute_plan(compute_plan_id)
```

Compute plans will get a new "status" property. It will have to be added to the printers in both list and single item displays.

And of course, all of this will need to be tested properly.

**Comment by Kelvin-M** [comment]
@jmorel This PR (https://github.com/SubstraFoundation/substra/pull/56) was merged, did it fix your issue ?

**Comment by jmorel** [comment]
Absolutely! I'm closing the issue.
