### ISSUE TITLE
Add debug for the CLI's tests

### ISSUE THREAD

**Issue by maeldebon** [SubstraFoundation/substra#58]
Currently, this is really hard to debug the CLI.
It could be good to add some information when a test crashes.
For instance, the full traceback, the exc_code, etc.

**Comment by Kelvin-M** [comment]
You can also use pytest option with `addopts` option like this  `python setup.py test --addopts='--capture no'`. 

You can also launch one test like this : 
`python setup.py test --addopts='tests/sdk/test_rest_client.py::test_add_exist_ok' `

**Comment by samlesu** [comment]
Fixed by #61
