### ISSUE TITLE
mock_requests returns a mock that is always called

### ISSUE THREAD

**Issue by jmorel** [SubstraFoundation/substra#83]
In lots of places, we use mock_requests and check that the returned mock has been called. These `assert m.is_called()` are present everywhere. However it seems they don't work as we think they do. 

Here is a test that shouldn't pass:

```python
def test_foo(mocker):
    m = mock_requests(mocker, "post", response='foo')
    assert m.is_called()
```

But it does!

We need to investigate why it passes and update the mock_requests so that it works as we think it should.

**Comment by maeldebon** [comment]
Great catch! 👏 
I just checked the code of `mock_requests` and, indeed, a `m` is always returned, even when an exception is raised :

```
def mock_requests_response(response=None, status=200, headers=None):
    headers = headers or {}
    m = mock.MagicMock(spec=requests.Response)
    m.status_code = status
    m.headers = headers
    m.text = str(response)
    m.json = mock.MagicMock(return_value=response, headers=headers)

    if status not in (200, 201):
        exception = requests.exceptions.HTTPError(str(status), response=m)
        m.raise_for_status = mock.MagicMock(side_effect=exception)

    return m
```
