### ISSUE TITLE
Error when trying to add an objective during titanic example

### ISSUE THREAD

**Issue by chrisalexandrepena** [SubstraFoundation/substra#96]
I am trying to run the **add_dataset_objective.py** on my **ubuntu server 18.04.3 LTS** environment. Here is the error I get, even though the passwords are correctly specified in the config.json files :

```
Requests error status 400: {"password":["This field is required."]}
Traceback (most recent call last):
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 44, in login
    r.raise_for_status()
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://substra-backend.node-1.com:80/api-token-auth/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/add_dataset_objective.py", line 59, in <module>
    client.login()
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/client.py", line 86, in login
    res = self.client.login()
  File "/home/ubuntu/dev/substra/examples/titanic/.venv/lib/python3.6/site-packages/substra/sdk/rest_client.py", line 53, in login
    raise exceptions.BadLoginException.from_request_exception(e)
substra.sdk.exceptions.BadLoginException: 400 Client Error: Bad Request for url: http://substra-backend.node-1.com:80/api-token-auth/
```

The error gets fixed if I install the **keyrings.alt** dependency.

**Comment by chrisalexandrepena** [comment]
@jmorel :)

**Comment by chrisalexandrepena** [comment]
The problem was caused by keyring-alt:
The ubuntu packages `python3-keyrings.alt` and `python-keyrings.alt` were installed by default on the machine and were conflicting with the python dependencies. I solved the issue by uninstalling them (`sudo apt-get remove python3-keyrings.alt python-keyrings.alt`) and then installing them using pip3 (`pip3 install -U keyrings-alt`), and again locally if using a virtualenv.
We should add that to the doc @natct10

**Comment by Kelvin-M** [comment]
@chrisalexandrepena Is it link to https://github.com/SubstraFoundation/substra/issues/75 ?
It may be good to merge those two issue as it is link to keyring and add a troubleshoot section for keyring in the documentation ?

**Comment by natct10** [comment]
It has been added to the documentation update proposed here: https://github.com/SubstraFoundation/substra/pull/110/files#

**Comment by chrisalexandrepena** [comment]
@Kelvin-M yes it is a similar problem, let's merge the two issues

**Comment by jmorel** [comment]
Closing this as a proper error message has been introduced in #121.
